from extractdata import *
from os.path import isdir
from os import system, mkdir

system("cls||clear")
entrie = input("Entrie archive: ")
name, output = openImage(entrie)
if not isdir(name): mkdir(name)
output = cutImage(output)
cv.imwrite(f"{name}/cutted.png", output)
output = claheFilter(output)
cv.imwrite(f"{name}/clahe.png", output)
canny = cannyFilter(output)
cv.imwrite(f"{name}/canny.png", canny)
deleted, estimated = estimateBack(canny)
cv.imwrite(f"{name}/estim.png", estimated)
cv.imwrite(f"{name}/delete.png", deleted)
thread1 = rThread(target = xFilter, args = [deleted])
thread2 = rThread(target = xFilter, args = [estimated])
thread1.start(); thread2.start()
deleted = thread1.join()
estimated = thread2.join()
cv.imwrite(f"{name}/filter1.png", deleted)
cv.imwrite(f"{name}/filter2.png", estimated)
output = juntarImgs(estimated, deleted)
cv.imwrite(f"{name}/juntos.png", output)
thread1 = rThread(target = extract, args = [deleted, name, 1])
thread2 = Thread(target = extract, args = [estimated, name, 2])
thread1.start(); thread2.start()
saida1 = thread1.join()
thread2.join()
thread1 = rThread(target = sobrepor, args = [output, saida1])
thread2 = rThread(target = sobrepor, args = [canny, saida1])
thread1.start(); thread2.start()
saida1 = thread1.join()
saida2 = thread2.join()
cv.imwrite(f"{name}/sobre1.png", saida1)
cv.imwrite(f"{name}/sobre2.png", saida2)
print("Processo Terminado!")