from extractdata import *
from os import system

system("cls||clear")
name, output = openImage(input("Entrie archive: "))
if not isdir(name): mkdir(name)
output = cutImage(output)
cv.imwrite(f"{name}/cutted.png", output)
output = claheFilter(output)
cv.imwrite(f"{name}/clahe.png", output)
canny = cannyFilter(output)
cv.imwrite(f"{name}/canny.png", canny)
deleted, estimat = estimateBack(canny)
cv.imwrite(f"{name}/estimat.png", estimat)
cv.imwrite(f"{name}/deleted.png", deleted)
thread1 = rThread(target = xFilter2, args = [deleted])
thread2 = rThread(target = xFilter2, args = [estimat])
thread1.start(); thread2.start()
deleted, estimat = thread1.join(), thread2.join()
cv.imwrite(f"{name}/filter1.png", deleted)
cv.imwrite(f"{name}/filter2.png", estimat)
output = juntarImgs(estimat, deleted)
cv.imwrite(f"{name}/juntos.png", output)
thread1 = rThread(target = extract, args = [deleted, name, 1])
thread2 = rThread(target = extract, args = [estimat, name, 2])
thread1.start(); thread2.start()
imagem, lista1 = thread1.join()
lista2 = thread2.join()[1]
writeArch(name, lista1, lista2)
thread1 = rThread(target = sobrepor, args = [output, imagem])
thread2 = rThread(target = sobrepor, args = [canny, imagem])
thread1.start(); thread2.start()
saida1, saida2 = thread1.join(), thread2.join()
cv.imwrite(f"{name}/sobre1.png", saida1)
cv.imwrite(f"{name}/sobre2.png", saida2)
print("Processo Terminado!")