if (lpmalgos_HELPERS)
  return()
endif()
set(lpmalgos_HELPERS ON)

function(add_lpmalgos_python_module NAME) 
  add_library(${NAME} MODULE ${ARGN})
  set_target_properties(${NAME} PROPERTIES OUTPUT_NAME_${CMAKE_BUILD_TYPE} "${NAME}")
  set_target_properties(${NAME} PROPERTIES OUTPUT_NAME "${NAME}")
  set_target_properties(${NAME} PROPERTIES PREFIX "${PYTHON_MODULE_PREFIX}"
                                           SUFFIX "${PYTHON_MODULE_EXTENSION}")
  if (APPLE)
    set_target_properties(${NAME} OUTPUT_NAME ${NAME} LINK_FLAGS "-undefined dynamic_lookup")
  endif()
  set_property(TARGET ${NAME} PROPERTY C_VISIBILITY_PRESET hidden)
  set_property(TARGET ${NAME} PROPERTY CXX_VISIBILITY_PRESET hidden)
endfunction()

function(add_lpmalgos_executable NAME)
  add_executable(${NAME} ${ARGN})
  if (APPLE)
    set_target_properties(${NAME} OUTPUT_NAME ${NAME} LINK_FLAGS "-undefined dynamic_lookup")
  endif()
  set_property(TARGET ${NAME} PROPERTY C_VISIBILITY_PRESET hidden)
  set_property(TARGET ${NAME} PROPERTY CXX_VISIBILITY_PRESET hidden)
endfunction()
